<a href="https://colab.research.google.com/github/taetaecelc/bancodedados/blob/main/C%C3%B3pia_de_2ds_bd_criar_bd_MySQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROJETO: CRIAÇÃO DE BANCO DE DADOS COM MYSQL

In [27]:
# Instala o MySQL
!apt-get update
!apt-get install -y mysql-server

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mysql-server is already the newest version (8.0.45-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 104 not upgraded.

In [28]:
# Inicia o serviço do SGDB MySQL
!service mysql start

 * Starting MySQL database server mysqld
   ...done.

In [29]:
# Configura o MySQL e cria o banco de dados (execute só 1 vez, para executar de novo deve trocar nomes de banco e usuário)
!mysql -e "CREATE DATABASE Escola;" && echo "Banco de dados 'Escola' criado com sucesso."
!mysql -e "CREATE USER 'adm'@'localhost' IDENTIFIED BY 'senha';" && echo "Usuário 'adm' criado com sucesso."
!mysql -e "GRANT ALL PRIVILEGES ON Escola.* TO 'adm'@'localhost';" && echo "Privilégios concedidos ao usuário 'adm'."
!mysql -e "FLUSH PRIVILEGES;" && echo "Privilégios atualizados com sucesso."

ERROR 1007 (HY000) at line 1: Can't create database 'Escola'; database exists
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'adm'@'localhost'
Privilégios concedidos ao usuário 'adm'.
Privilégios atualizados com sucesso.

In [30]:
# Exlclui o banco de dados
#!mysql -e "DROP DATABASE Escola;" && echo "Banco de dados 'Escola' excluído com sucesso."

# Exlcui usuario do banco de dados
#!mysql -e "DROP USER 'name'@'localhost';" && echo "Usuário 'name' excluído com sucesso."

In [31]:
# Instala a biblioteca mysql.connector
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.6.0)

In [32]:
# Importa biblioteca mysql.connector
import mysql.connector
from mysql.connector import Error

try:
    # Conecta ao banco de dados Escola
    conn = mysql.connector.connect(
        host="localhost",
        user="adm",
        password="senha",
        database="Escola"
    )
    # Imprime mensagens para confirmar a conexão
    if conn.is_connected():
        print("Conexão realizada com sucesso.")

    cursor = conn.cursor()

except Error as e:
    print(f"Erro ao conectar ao MySQL: {e}")

Conexão realizada com sucesso.

In [33]:
# Cria tabelas no bd Escola
cursor.execute("CREATE TABLE Alunos (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, data_nascimento DATE NOT NULL, endereco VARCHAR(255) NOT NULL, serie INT NOT NULL);")
cursor.execute("CREATE TABLE Professores (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, especialidade VARCHAR(100) NOT NULL, data_contratacao DATE NOT NULL);")
cursor.execute("CREATE TABLE Disciplinas (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, carga_horaria INT NOT NULL);")

ProgrammingError: 1050 (42S01): Table 'Alunos' already exists

In [34]:
# Exclui tabelas do banco de dados
#cursor.execute("DROP TABLE IF EXISTS Alunos1;")
#cursor.execute("DROP TABLE IF EXISTS Professores1;")
#cursor.execute("DROP TABLE IF EXISTS Disciplinas1;")

In [26]:
 # Exibe as tabelas criadas
 cursor.execute("SHOW TABLES;")
 tables = cursor.fetchall()
 print("Tabelas no banco de dados 'Escola:")
 for table in tables:
  print(table[0])

ProgrammingError: Cursor is not connected

In [24]:
# Apagar tabelas com "1" no nome
tabelas_para_apagar = ["Alunos1", "Disciplinas1", "Professores1"]
for tabela in tabelas_para_apagar:
  try:
    cursor.execute(f"DROP TABLE IF EXISTS {tabela};")
    print(f"Tabela '{tabela}' apagada com sucesso.")
  except Error as e:
    print(f"Erro ao apagar a tabela '{tabela}': {e}")

Erro ao apagar a tabela 'Alunos1': Cursor is not connected
Erro ao apagar a tabela 'Disciplinas1': Cursor is not connected
Erro ao apagar a tabela 'Professores1': Cursor is not connected

In [25]:
# Insere dados nas tabelas
cursor.execute("INSERT INTO Alunos (nome, data_nascimento, endereco, serie) VALUES ('João Silva', '2005-05-15', 'Rua A, 123', 2), ('Maria Oliveira', '2006-08-22', 'Rua B, 456', 2);")
cursor.execute("INSERT INTO Professores (nome, especialidade, data_contratacao) VALUES ('Carlos Souza', 'Matemática', '2020-02-01'), ('Ana Lima', 'Português', '2019-03-15');")
cursor.execute("INSERT INTO Disciplinas (nome, carga_horaria) VALUES ('Matemática', 200), ('Português', 180);")

ProgrammingError: Cursor is not connected

In [19]:
# Importa biblioteca Pandas
import pandas as pd

# Função para exibir dados de uma tabela em formato de DataFrame
def exibir_tabela(nome_tabela):
  cursor.execute(f"SELECT * FROM {nome_tabela};")
  rows = cursor.fetchall()
  colunas = [desc[0] for desc in cursor.description]
  df = pd.DataFrame(rows, columns=colunas)
  print(f"\nDados da tabela {nome_tabela}:")
  display(df)

# Exibe tabelas criadas
cursor.execute("SHOW TABLES;")
tables = cursor.fetchall()
print("Tabelas no banco de dados 'Escola':")
for table in tables:
  print(table[0])
  exibir_tabela(table[0])

Tabelas no banco de dados 'Escola':
Alunos

Dados da tabela Alunos:

   id            nome data_nascimento    endereco  serie
0   1      João Silva      2005-05-15  Rua A, 123      2
1   2  Maria Oliveira      2006-08-22  Rua B, 456      2

Disciplinas

Dados da tabela Disciplinas:

   id        nome  carga_horaria
0   1  Matemática            200
1   2   Português            180

Professores

Dados da tabela Professores:

   id          nome especialidade data_contratacao
0   1  Carlos Souza    Matemática       2020-02-01
1   2      Ana Lima     Português       2019-03-15

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [20]:
# Consulta dados na tabela Alunos
cursor.execute("SELECT * FROM Alunos;")
for row in cursor.fetchall():
    print(row)

(1, 'João Silva', datetime.date(2005, 5, 15), 'Rua A, 123', 2)
(2, 'Maria Oliveira', datetime.date(2006, 8, 22), 'Rua B, 456', 2)

In [21]:
# Consulta dados na tabela Professores
cursor.execute("SELECT * FROM Professores;")
for row in cursor.fetchall():
    # Formata a data como string (texto)
    id, nome, especialidade, data_contratacao = row
    print(f"ID: {id}, Nome: {nome}, Especialidade: {especialidade}, Data de Contratação: {data_contratacao.strftime('%Y-%m-%d')}")

ID: 1, Nome: Carlos Souza, Especialidade: Matemática, Data de Contratação: 2020-02-01
ID: 2, Nome: Ana Lima, Especialidade: Português, Data de Contratação: 2019-03-15

In [22]:
# Consulta dados na tabela Disciplinas
cursor.execute("SELECT * FROM Disciplinas;")
for row in cursor.fetchall():
    print(row)

(1, 'Matemática', 200)
(2, 'Português', 180)

In [23]:
# Fecha a conexão com o SGDB MySQL
try:
    cursor.close()
    conn.close()
    print("Conexão fechada com sucesso.")
except Error as e:
    print(f"Erro ao fechar a conexão com MySQL: {e}")

Conexão fechada com sucesso.